e: 0.12
SizeX: 70
SizeY: 70
RangeX: 
  Item1: 0
  Item2: 0.5
RangeY: 
  Item1: 0
  Item2: 0.5
Integrator:
  Order: 4
  Timestep: 0.01
Visualization:
  Fade: 3
  RangeX:
    Item1: -3
    Item2: 3
  RangeY:
    Item1: -3
    Item2: 3